from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database import get_db
from app import models
from app.core.jwt import get_current_user
from app.core.ai_engine import generate_tasks_from_note

router = APIRouter(prefix="/ai", tags=["AI"])


@router.post("/note/{note_id}/create-tasks")
def create_tasks_from_note(
    note_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    note = db.query(models.Note).filter(
        models.Note.id == note_id,
        models.Note.owner_id == current_user.id
    ).first()

    if not note:
        raise HTTPException(status_code=404, detail="Note not found")

    task_titles = generate_tasks_from_note(note.content)

    created_tasks = []

    for title in task_titles:
        task = models.Task(
            title=title,
            description="Generated by AI",
            owner_id=current_user.id
        )
        db.add(task)
        created_tasks.append(title)

    db.commit()

    return {
        "message": "AI tasks created successfully",
        "tasks": created_tasks
    }
