from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database import get_db
from app import models
from app.core.jwt import get_current_user
from app.core.ai_engine import (
    generate_tasks_from_note,
    generate_qa_from_note,
    answer_user_question,
)
from app.schemas import AIQuestion, AIHistoryOut
from app.core.ai_engine import generate_study_schedule
from app.core.ai_engine import generate_priority_schedule
from app.core.ai_engine import generate_exam_revision_plan
from app.core.ai_engine import generate_productivity_insight

router = APIRouter(prefix="/ai", tags=["AI"])


# ==============================
# CREATE TASKS FROM NOTE (AI)
# ==============================
@router.post("/note/{note_id}/create-tasks")
def create_tasks_from_note(
    note_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    note = db.query(models.Note).filter(
        models.Note.id == note_id,
        models.Note.owner_id == current_user.id,
    ).first()

    if not note:
        raise HTTPException(status_code=404, detail="Note not found")

    task_titles = generate_tasks_from_note(note.content)

    created_tasks = []

    for title in task_titles:
        task = models.Task(
            title=title,
            description="Generated by AI",
            owner_id=current_user.id,
        )
        db.add(task)
        created_tasks.append(title)

    db.commit()

    return {
        "message": "AI tasks created successfully",
        "tasks": created_tasks,
    }


# ==============================
# GENERATE Q&A FROM NOTE (AI)
# ==============================
@router.get("/note/{note_id}/qa")
def generate_qa(
    note_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    note = db.query(models.Note).filter(
        models.Note.id == note_id,
        models.Note.owner_id == current_user.id,
    ).first()

    if not note:
        raise HTTPException(status_code=404, detail="Note not found")

    qa = generate_qa_from_note(note.content)

    return {
        "note_id": note.id,
        "qa": qa,
    }


# ==============================
# ASK AI QUESTION + SAVE HISTORY
# ==============================
@router.post("/ask", response_model=AIHistoryOut)
def ask_ai(
    data: AIQuestion,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    answer = answer_user_question(data.question)

    history = models.AIHistory(
        question=data.question,
        answer=answer,
        owner_id=current_user.id,
    )

    db.add(history)
    db.commit()
    db.refresh(history)

    return history


# ==============================
# GET AI HISTORY OF USER
# ==============================
@router.get("/history", response_model=list[AIHistoryOut])
def get_ai_history(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    return db.query(models.AIHistory).filter(
        models.AIHistory.owner_id == current_user.id
    ).all()

@router.get("/study-schedule")
def get_study_schedule(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    pending_tasks = db.query(models.Task).filter(
        models.Task.owner_id == current_user.id,
        models.Task.completed == False
    ).all()

    schedule = generate_study_schedule(pending_tasks)

    return {
        "total_tasks": len(pending_tasks),
        "schedule": schedule
    }
@router.get("/priority-schedule")
def get_priority_schedule(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    pending_tasks = db.query(models.Task).filter(
        models.Task.owner_id == current_user.id,
        models.Task.completed == False
    ).all()

    schedule = generate_priority_schedule(pending_tasks)

    return {
        "total_pending": len(pending_tasks),
        "priority_schedule": schedule
    }
@router.get("/exam-revision")
def get_exam_revision_plan(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    pending_tasks = db.query(models.Task).filter(
        models.Task.owner_id == current_user.id,
        models.Task.completed == False
    ).all()

    plan = generate_exam_revision_plan(pending_tasks)

    return {
        "pending_topics": len(pending_tasks),
        "revision_plan": plan
    }
@router.get("/productivity")
def get_productivity_insight(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    total_tasks = db.query(models.Task).filter(
        models.Task.owner_id == current_user.id
    ).count()

    completed_tasks = db.query(models.Task).filter(
        models.Task.owner_id == current_user.id,
        models.Task.completed == True
    ).count()

    insight = generate_productivity_insight(total_tasks, completed_tasks)

    percent = (completed_tasks / total_tasks * 100) if total_tasks else 0

    return {
        "total_tasks": total_tasks,
        "completed_tasks": completed_tasks,
        "pending_tasks": total_tasks - completed_tasks,
        "completion_percentage": round(percent, 2),
        "ai_feedback": insight
    }
